name: Run YOLOv9 pipeline on self-hosted runner

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - 'training/yolov9_pipeline.py'
  workflow_dispatch:          # enables the “Run workflow” button in Actions

jobs:
  run-pipeline:
    runs-on: [self-hosted, clearml, yolo]   # must match the labels you set
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ClearML pipeline
        env:
          CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
          CLEARML_API_SERVER:     ${{ secrets.CLEARML_API_SERVER }}
          CLEARML_FILES_SERVER:   ${{ secrets.CLEARML_FILES_SERVER }}
          CLEARML_WEB_SERVER:     ${{ secrets.CLEARML_WEB_SERVER }}
        run: |
          cd training
          python yolov9_pipeline.py 
